
// BIND_AIR_AS_TX

#ifdef BIND_AIR_INSTANCE_INCLUDE_GLOBAL
_NAPI_BOUND(BIND_PATH,set_interleave,void,uint32_t);
_NAPI_BOUND(BIND_PATH,set_rs,int,uint32_t);

_NAPI_BOUND(BIND_PATH,set_duplex_mode,void,bool);
_NAPI_BOUND(BIND_PATH,get_duplex_mode,bool,void);

_NAPI_MEMBER(BIND_PATH,print4,unsigned);
_NAPI_MEMBER(BIND_PATH,print12,unsigned);
_NAPI_MEMBER(BIND_PATH,print1,bool);
_NAPI_MEMBER(BIND_PATH,print2,bool);
_NAPI_MEMBER(BIND_PATH,print3,bool);
_NAPI_MEMBER(BIND_PATH,print8,bool);
_NAPI_MEMBER(BIND_PATH,print9,bool);
_NAPI_MEMBER(BIND_PATH,print10,bool);
_NAPI_MEMBER(BIND_PATH,print11,bool);
_NAPI_MEMBER(BIND_PATH,print13,bool);
_NAPI_MEMBER(BIND_PATH,print14,bool);
_NAPI_MEMBER(BIND_PATH,print6,bool);
_NAPI_MEMBER(BIND_PATH,print15,bool);
_NAPI_MEMBER(BIND_PATH,print7,bool);
_NAPI_MEMBER(BIND_PATH,print16,bool);
_NAPI_MEMBER(BIND_PATH,print20,bool);
_NAPI_MEMBER(BIND_PATH,print21,bool);
_NAPI_MEMBER(BIND_PATH,print23,bool);
_NAPI_MEMBER(BIND_PATH,print24,bool);
_NAPI_MEMBER(BIND_PATH,print25,bool);
_NAPI_MEMBER(BIND_PATH,print26,bool);
_NAPI_MEMBER(BIND_PATH,print5,bool);
_NAPI_MEMBER(BIND_PATH,print17,bool);
_NAPI_MEMBER(BIND_PATH,print18,bool);
_NAPI_MEMBER(BIND_PATH,print19,bool);
_NAPI_MEMBER(BIND_PATH,print22,bool);
_NAPI_MEMBER(BIND_PATH,print27,bool);

_NAPI_MEMBER(BIND_PATH,duplex_start_frame,uint32_t);
_NAPI_BOUND(BIND_PATH,get_rs,int,void);
_NAPI_BOUND(BIND_PATH,get_interleaver,int,void);
_NAPI_BOUND(BIND_PATH,getLengthForInput, uint32_t, uint32_t);
_NAPI_BOUND(BIND_PATH,enablePrint, void, string);
_NAPI_BOUND(BIND_PATH,disablePrint, void, string);

#ifdef BIND_AIR_AS_TX
_NAPI_BOUND(BIND_PATH,resetTxSeq, void, void);
#else
_NAPI_MEMBER(BIND_PATH,dump1,bool);
#endif
#endif
#undef BIND_AIR_INSTANCE_INCLUDE_GLOBAL





#ifdef BIND_AIR_INSTANCE_INCLUDE_SCOPE
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print12);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print4);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print1);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print2);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print3);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print8);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print9);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print10);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print11);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print13);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print14);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print6);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print15);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print7);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print16);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print20);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print21);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print23);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print24);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print25);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print26);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print5);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print17);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print18);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print19);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print22);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, print27);
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, duplex_start_frame);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, set_interleave);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, set_rs);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, get_interleaver);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, get_rs);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, set_duplex_mode);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, get_duplex_mode);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, getLengthForInput);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, enablePrint);
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, disablePrint);

#ifdef BIND_AIR_AS_TX
  _NAPI_GENERIC_INIT(SUBTREE_OBJECT, resetTxSeq);
#else
  _NAPI_MEMBER_INIT(SUBTREE_OBJECT, dump1);
#endif
#endif
#undef BIND_AIR_INSTANCE_INCLUDE_SCOPE




#undef BIND_PATH
#undef SUBTREE_OBJECT
